BeautyCarePlus_App_ASP/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeautyCarePlus_App_ASP.Models
{
    public class Customer
    {
        
        public int Id { get; set; }

        [Display(Name = "Naam")]
        public string Name { get; set; }

        [Display(Name = "Geboortedatum")]
        public DateTime BirthDate { get; set; }

        public double InitialWeight { get; set; }

        public int TurnsLeft { get; set; }

        public string Adres { get; set; }

        public MeasuringHeights MeasuringHeights { get; set; }

    }
}

BeautyCarePlus_App_ASP/Models/DatabaseService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BeautyCarePlus_App_ASP.Models
{
    public class DatabaseService
    {
        public List<Customer> CustomerList { get; set; }
    }
}

BeautyCarePlus_App_ASP/Models/Gebruiker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeautyCarePlus_App_ASP.Models
{
    public class Gebruiker
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        [Required]
        [StringLength(255)]
        public string Email { get; set; }
        [Required]
        [StringLength(255)]
        public string Paswoord { get; set; }
    }
}

BeautyCarePlus_App_ASP/Models/MeasuringHeights.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeautyCarePlus_App_ASP.Models
{
    public class MeasuringHeights
    {
        public int Id { get; set; }

        [Display(Name = "Taille")]
        public double Waist { get; set; }

        public double Hip { get; set; }

        [Display(Name = "Dij")]
        public double Thigh { get; set; }

        public double Arm { get; set; }

        [Display(Name = "Kuit")]
        public double Calf { get; set; }

        [Display(Name = "Knie")]
        public double Knee { get; set; }

        [Display(Name = "Opmerking")]
        public string Comment { get; set; }
    }
}

BeautyCarePlus_App_ASP/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeautyCarePlus_App_ASP.Models
{
    public class User
    {
        public int Id { get; set; }
        [Display(Name = "Naam")]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string Email { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Wachtwoord")]
        public string Password { get; set; }
    }
}

BeautyCarePlus_App_ASP/ViewModels/CustomersListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BeautyCarePlus_App_ASP.Models;

namespace BeautyCarePlus_App_ASP.ViewModels
{
    public class CustomersListViewModel
    {
        public List<Customer> CustomerList { get; set; }
    }
}

BeautyCarePlus_App_ASP/ViewModels/GebruikerLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BeautyCarePlus_App_ASP.Models;

namespace BeautyCarePlus_App_ASP.ViewModels
{
    public class GebruikerLoginViewModel
    {
        public string Email { get; set; }
        public string Paswoord { get; set; }

    }
}

BeautyCarePlus_App_ASP/ViewModels/UserLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BeautyCarePlus_App_ASP.Models;

namespace BeautyCarePlus_App_ASP.ViewModels
{
    public class UserLoginViewModel
    {
        public string Email { get; set; }
        public string Wachtwoord { get; set; }

    }
}

BeautyCarePlus_App_ASP/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeautyCarePlus_App_ASP.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }
    }
}

BeautyCarePlus_App_ASP/Controllers/CostumersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeautyCarePlus_App_ASP.Models;
using BeautyCarePlus_App_ASP.ViewModels;

namespace BeautyCarePlus_App_ASP.Controllers
{
    
    //[Authorize]
    public class CostumersController : Controller
    {
        public DatabaseService databaseService = new DatabaseService();

        // GET: Account
        public ActionResult CustomersList()
        {
            CustomersListViewModel viewModel = new CustomersListViewModel();
            viewModel.CustomerList = new List<Customer>();
            viewModel.CustomerList.Add(new Customer()
            {
                Name = "Mathieu Broeckhoven",
                Adres = "Peulisbaan 124F 2580 Putte",
                BirthDate = new DateTime(1998, 12, 27),
                InitialWeight = 60.5
            }) ;
                viewModel = new CustomersListViewModel();
                return View(viewModel);
        }
    }
}

BeautyCarePlus_App_ASP/Controllers/GebruikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeautyCarePlus_App_ASP.Models;
using BeautyCarePlus_App_ASP.ViewModels;

namespace BeautyCarePlus_App_ASP.Controllers
{
    public class GebruikerController : Controller
    {
        public ActionResult GebruikerLoginView()
        {
            var viewModel = new GebruikerLoginViewModel();
            return View(viewModel);
        }

        public ActionResult LogIn(Gebruiker gebruiker)
        {

            return Content("GebruikerLogin wordt nog niet geredirect");
        }
    }
}

BeautyCarePlus_App_ASP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeautyCarePlus_App_ASP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BeautyCarePlus_App_ASP/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeautyCarePlus_App_ASP.Models;
using BeautyCarePlus_App_ASP.ViewModels;

namespace BeautyCarePlus_App_ASP.Controllers
{
    public class UserController : Controller
    {
        public ActionResult UserLoginView()
        {
            var viewModel = new UserLoginViewModel();
            return View(viewModel);
        }

        public ActionResult LogIn(User user)
        {

            return Content("GebruikerLogin wordt nog niet geredirect");
        }
    }
}

BeautyCarePlus_App_ASP/Views/Customers/CustomersListView.cshtml
@model BeautyCarePlus_App_ASP.ViewModels.CustomersListViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Klanten</h2>

@if (Model.CustomerList.Count == 0)
{
    <text>Geen klanten om weer te geven.</text>
}
else
{
<ul>
    @foreach (var customer in Model.CustomerList)
    {
        <li>@customer.Name</li>
        <li>@customer.Adres</li>
        <li>@customer.BirthDate</li>
        <li>@customer.InitialWeight</li>
    }
</ul>  
}

BeautyCarePlus_App_ASP/Views/Gebruiker/GebruikerLoginView.cshtml
@using System.Activities.Expressions
@using System.Web.Mvc.Html
@model BeautyCarePlus_App_ASP.ViewModels.GebruikerLoginViewModel
@{
    ViewBag.Title = "Log In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gebruiker login</h2>

@using (Html.BeginForm("LogIn", "Gebruiker"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Paswoord)
        @Html.TextBoxFor(m => m.Paswoord, new {@class = "form-control"})
    </div>
    <button type="submit" class="btn btn-primary">Log in</button>
}

BeautyCarePlus_App_ASP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BeautyCarePlus_App_ASP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BeautyCarePlus_App_ASP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BeautyCarePlus_App_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Beauty Care +</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@*<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <div class="navbar-header">
            @Html.ActionLink("Beauty Care +", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
               
        </div>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="nav-item">@Html.ActionLink("About", "About", "Home")</li>
                <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>*@
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        @Html.ActionLink("Beauty Care +", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarColor01" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Klanten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Afspraken</a>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>*@
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Beheer</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="#">Inloggen</a>
                </li>
            </ul>
            @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>*@
            
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - by MB-Development</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BeautyCarePlus_App_ASP/Views/User/UserLoginView.cshtml
@using System.Activities.Expressions
@using System.Web.Mvc.Html
@model BeautyCarePlus_App_ASP.ViewModels.UserLoginViewModel
@{
    ViewBag.Title = "Log In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gebruiker login</h2>

@using (Html.BeginForm("LogIn", "User"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Wachtwoord)
        @Html.TextBoxFor(m => m.Wachtwoord, new {@class = "form-control"})
    </div>
    <button type="submit" class="btn btn-primary">Log in</button>
}